from __future__ import annotations

from typing import AsyncIterator, Optional

class ClientConfig:
    key_path: Optional[str]
    entry_node: str
    hop_count: int
    cashu_mint_url: str
    listen_addr: str
    bootstrap_peers: list[str]
    peer_store_path: Optional[str]
    yggdrasil_only: bool

    def __init__(self) -> None: ...

class ReceiveStream:
    def __aiter__(self) -> "ReceiveStream": ...
    async def __anext__(self) -> bytes: ...

class ZksnClient:
    @staticmethod
    async def connect(config: ClientConfig) -> "ZksnClient": ...
    def fingerprint(self) -> str: ...
    def routing_pubkey_hex(self) -> str: ...
    async def peer_count(self) -> int: ...
    async def send(self, recipient_pubkey_hex: str, payload: bytes) -> None: ...
    async def receive(self) -> ReceiveStream: ...
