[http]
enabled = true
address = 127.0.0.1
port    = 7070

[httpproxy]
enabled = true
address = 0.0.0.0
port    = 4444

[socksproxy]
enabled = true
address = 0.0.0.0
port    = 4447

[ntcp2]
enabled = true

[sam]
enabled = false
