// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "../contracts/ZKSNGovernance.sol";
import "../contracts/MockVerifier.sol";
import "../contracts/Groth16Verifier.sol";
import "../contracts/PoseidonHasher.sol";

/**
 * @title ZKSNGovernanceTest
 *
 * Test suite covering:
 *   1. Governance logic (proposal lifecycle, voting, quorum, timelock, execution)
 *      — uses StrictMockVerifier for determinism
 *   2. Groth16Verifier correctness — real verifier rejects invalid proofs,
 *      validates proof encoding, validates field element bounds
 *   3. Signal layout — verifies castVote passes signals in the order the
 *      circuit expects: [nullifierHash, proposalId, voteYes, membershipRoot]
 *   4. Deployment path — Groth16Verifier is wired as IVerifier; MockVerifier
 *      is explicitly NOT used in the production governance instance
 *   5. PoseidonHasher consistency — leaf/nullifier derivation matches expected
 *      Poseidon semantics (format, range)
 */
contract ZKSNGovernanceTest is Test {
    // ── fixtures ──────────────────────────────────────────────────────────────

    ZKSNGovernance gov; // uses StrictMockVerifier (governance logic tests)
    ZKSNGovernance groth16Gov; // uses real Groth16Verifier (verifier tests)
    MockVerifier mock;
    StrictMockVerifier strict;
    Groth16Verifier realVerifier;
    PoseidonHasher hasher;

    bytes32 constant ROOT = keccak256("initial_root");
    bytes constant PROOF = hex"deadbeef";

    // Valid 256-byte proof encoding (a, b, c all zero — fails pairing with real VK)
    bytes constant ZERO_PROOF = abi.encode(
        [uint256(0), uint256(0)], // a
        [[uint256(0), uint256(0)], [uint256(0), uint256(0)]], // b
        [uint256(0), uint256(0)] // c
    );

    // ── Real proof from ceremony ───────────────────────────────────────────────
    //
    // Generated by: node circuits/prove.js (see circuits/prove.js)
    // Circuit: MembershipVote (depth=4, 1422 constraints)
    // Input:
    //   secret        = 12345678901234567890
    //   proposalId    = 999888777666555444333222111
    //   voteYes       = 1
    //   pathIndices   = [0,0,0,0]
    //   pathElements  = [111222333444555666777888999, 999111222333444555666777888,
    //                    444555666777888999000111222, 777888999000111222333444555]
    //
    // Public signals (verified by snarkjs groth16 verify ✅):
    //   nullifierHash  = 7111602497682809495639497939057765305932059429149913821046653318829258540568
    //   proposalId     = 999888777666555444333222111
    //   voteYes        = 1
    //   membershipRoot = 19748651011774828787493657306186640906239354906814775894613021125601476386351
    // Proof from ZKSN 3-contributor MPC ceremony — MembershipVote(depth=4), pot12.
    // Input: secret=12345678901234567890, tree index=0, proposalId=999888777666555.
    // G2 Fp2 coords stored in EIP-197 order: (imaginary, real).
    // See ceremony/ATTESTATION.md for contribution hashes.
    bytes constant REAL_PROOF =
        hex"2d41401779fb6b5408e811358589d16a337bac148543b8bb292880dc5d17f3ff"
        hex"12143fb3e11718fb0041c483e047d2532263357193d7ed3569f324a4e51f5883"
        hex"01485277aadf23e6be996b17b7f179c1d7cb717fded7ed9080b8ec588b16b9dd"
        hex"0b3ca537c7663440836beb2ccbf22fd931d607af48441b5b1758a54cefcdb7b4"
        hex"08df05b1f111c488cfd1b8bcedfbf2c8cb933f6752c374875e9b02ab5dc8c92f"
        hex"22fefb84aff026f9c9369adf1a23b90d5ec14d2be9a69cc29f64ec379009f07e"
        hex"12f76c095f4b42996d409bf3733c1cc813574dc6a296308f2949c8e4e2629de9"
        hex"271b2146d5934a5a099f732a2cb898414ed6e2af17e2d8e1dad183dbd8b0da8e";

    uint256 constant REAL_NULLIFIER =
        21605468119089894529364334093527017674406608084847384275934021833321276526684;
    uint256 constant REAL_PROPOSAL_ID = 999888777666555;
    uint256 constant REAL_MEMBERSHIP_ROOT =
        4822649595394777945015941726176441426730374852172943875568241182555177324233;

    function setUp() public {
        mock = new MockVerifier();
        strict = new StrictMockVerifier();
        realVerifier = new Groth16Verifier();
        hasher = new PoseidonHasher();

        // Governance logic tests — StrictMockVerifier (pre-approve PROOF)
        gov = new ZKSNGovernance(address(strict), ROOT);
        strict.approve(PROOF);

        // Verifier tests — real Groth16Verifier, membership root from ceremony
        groth16Gov = new ZKSNGovernance(address(realVerifier), bytes32(REAL_MEMBERSHIP_ROOT));
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    function _proposal() internal returns (bytes32) {
        return gov.createProposal(keccak256("change"), address(0), "");
    }

    function _passProposal() internal returns (bytes32) {
        bytes32 id = _proposal();
        for (uint256 i = 0; i < 11; i++) {
            gov.castVote(id, keccak256(abi.encode("v", i)), true, PROOF);
        }
        vm.warp(block.timestamp + 8 days);
        gov.finalizeProposal(id);
        return id;
    }

    // ── 1. Governance logic tests (StrictMockVerifier) ────────────────────────

    function test_CreateProposal() public {
        bytes32 id = _proposal();
        (bytes32 ch,,,,,) = gov.getProposal(id);
        assertEq(ch, keccak256("change"));
    }

    function test_VoteYes() public {
        bytes32 id = _proposal();
        gov.castVote(id, keccak256("voter1"), true, PROOF);
        (,, uint256 yes,,,) = gov.getProposal(id);
        assertEq(yes, 1);
    }

    function test_VoteNo() public {
        bytes32 id = _proposal();
        gov.castVote(id, keccak256("voter1"), false, PROOF);
        (,,, uint256 no,,) = gov.getProposal(id);
        assertEq(no, 1);
    }

    function test_DoubleVotePrevented() public {
        bytes32 id = _proposal();
        bytes32 nul = keccak256("voter1");
        gov.castVote(id, nul, true, PROOF);
        vm.expectRevert("Already voted");
        gov.castVote(id, nul, true, PROOF);
    }

    function test_VoteAfterDeadlineFails() public {
        bytes32 id = _proposal();
        vm.warp(block.timestamp + 8 days);
        vm.expectRevert("Voting period ended");
        gov.castVote(id, keccak256("late"), true, PROOF);
    }

    function test_QuorumRequired() public {
        bytes32 id = _proposal();
        for (uint256 i = 0; i < 9; i++) {
            gov.castVote(id, keccak256(abi.encode("v", i)), true, PROOF);
        }
        vm.warp(block.timestamp + 8 days);
        gov.finalizeProposal(id);
        (,,,,, bool passed) = gov.getProposal(id);
        assertFalse(passed);
    }

    function test_PassesWithMajority() public {
        bytes32 id = _passProposal();
        (,,,,, bool passed) = gov.getProposal(id);
        assertTrue(passed);
    }

    function test_FailsWithoutMajority() public {
        bytes32 id = _proposal();
        for (uint256 i = 0; i < 6; i++) {
            gov.castVote(id, keccak256(abi.encode("y", i)), true, PROOF);
        }
        for (uint256 i = 0; i < 6; i++) {
            gov.castVote(id, keccak256(abi.encode("n", i)), false, PROOF);
        }
        vm.warp(block.timestamp + 8 days);
        gov.finalizeProposal(id);
        (,,,,, bool passed) = gov.getProposal(id);
        assertFalse(passed);
    }

    function test_TimeLockEnforced() public {
        bytes32 id = _passProposal();
        vm.expectRevert("Time-lock active");
        gov.execute(id);
    }

    function test_ExecuteAfterTimeLock() public {
        bytes32 id = _passProposal();
        vm.warp(block.timestamp + 3 days);
        gov.execute(id);
        (,,,, bool executed,) = gov.getProposal(id);
        assertTrue(executed);
    }

    function test_DoubleExecutionPrevented() public {
        bytes32 id = _passProposal();
        vm.warp(block.timestamp + 3 days);
        gov.execute(id);
        vm.expectRevert("Already executed");
        gov.execute(id);
    }

    function test_HasVoted() public {
        bytes32 id = _proposal();
        bytes32 nul = keccak256("voter_check");
        assertFalse(gov.hasVoted(nul));
        gov.castVote(id, nul, true, PROOF);
        assertTrue(gov.hasVoted(nul));
    }

    function test_MembershipRootUpdateOnlyViaGovernance() public {
        vm.expectRevert("Only via governance");
        gov.updateMembershipRoot(keccak256("new_root"));
    }

    function test_ProposalNotFound() public {
        vm.expectRevert("Proposal not found");
        gov.castVote(bytes32(0), keccak256("v"), true, PROOF);
    }

    function test_ExecuteFailedProposalReverts() public {
        bytes32 id = _proposal();
        vm.warp(block.timestamp + 8 days);
        gov.finalizeProposal(id);
        vm.expectRevert("Proposal did not pass");
        gov.execute(id);
    }

    // ── 2. Groth16Verifier — real ceremony VK, real proof acceptance ─────────

    /// Real proof from ceremony verifies successfully end-to-end.
    function test_Groth16_RealProofAccepted() public {
        // proposalId must match what was used to generate the proof
        bytes32 id = bytes32(REAL_PROPOSAL_ID);

        // Create a proposal with the ceremony proposalId as its ID
        // by controlling the hash inputs (use vm.prank + predictable hash)
        // Simpler: deploy a governance with proposal pre-created at known ID
        ZKSNGovernance g = new ZKSNGovernance(address(realVerifier), bytes32(REAL_MEMBERSHIP_ROOT));
        bytes32 proposalId = g.createProposal(bytes32(REAL_PROPOSAL_ID), address(0), "");

        // The real nullifier is Poseidon(secret, proposalId_from_contract)
        // Since proposalId from createProposal != REAL_PROPOSAL_ID (it's a hash),
        // we use verifyProof directly to confirm the VK is live and correct.
        uint256[4] memory signals;
        signals[0] = REAL_NULLIFIER;
        signals[1] = REAL_PROPOSAL_ID;
        signals[2] = 1;
        signals[3] = REAL_MEMBERSHIP_ROOT;

        bool result = realVerifier.verifyProof(REAL_PROOF, signals);
        assertTrue(result, "Real ceremony proof must verify");
    }

    /// Real proof with tampered nullifier is rejected.
    function test_Groth16_TamperedNullifierRejected() public {
        uint256[4] memory signals;
        signals[0] = REAL_NULLIFIER + 1; // tampered
        signals[1] = REAL_PROPOSAL_ID;
        signals[2] = 1;
        signals[3] = REAL_MEMBERSHIP_ROOT;

        bool result = realVerifier.verifyProof(REAL_PROOF, signals);
        assertFalse(result, "Tampered nullifier must fail");
    }

    /// Real proof with tampered voteYes is rejected.
    function test_Groth16_TamperedVoteRejected() public {
        uint256[4] memory signals;
        signals[0] = REAL_NULLIFIER;
        signals[1] = REAL_PROPOSAL_ID;
        signals[2] = 0; // proof was generated for voteYes=1, this is a lie
        signals[3] = REAL_MEMBERSHIP_ROOT;

        bool result = realVerifier.verifyProof(REAL_PROOF, signals);
        assertFalse(result, "Tampered voteYes must fail");
    }

    /// Real proof with tampered root is rejected.
    function test_Groth16_TamperedRootRejected() public {
        uint256[4] memory signals;
        signals[0] = REAL_NULLIFIER;
        signals[1] = REAL_PROPOSAL_ID;
        signals[2] = 1;
        signals[3] = REAL_MEMBERSHIP_ROOT + 1; // tampered

        bool result = realVerifier.verifyProof(REAL_PROOF, signals);
        assertFalse(result, "Tampered root must fail");
    }

    /// Random bytes rejected as "Invalid ZK proof".
    function test_Groth16_RandomBytesRejected() public {
        bytes32 id = groth16Gov.createProposal(keccak256("prop"), address(0), "");
        vm.expectRevert("Invalid ZK proof");
        groth16Gov.castVote(id, keccak256("v1"), true, hex"deadbeef");
    }

    /// Wrong length proof (not 256 bytes) is rejected.
    function test_Groth16_WrongLengthProofRejected() public {
        bytes32 id = groth16Gov.createProposal(keccak256("prop"), address(0), "");
        vm.expectRevert("Invalid ZK proof");
        groth16Gov.castVote(id, keccak256("v1"), true, hex"0102030405");
    }

    /// Empty proof rejected.
    function test_Groth16_EmptyProofRejected() public {
        bytes32 id = groth16Gov.createProposal(keccak256("prop"), address(0), "");
        vm.expectRevert("Invalid ZK proof");
        groth16Gov.castVote(id, keccak256("v1"), true, "");
    }

    /// A 256-byte zero proof fails pairing with real VK.
    function test_Groth16_ZeroProofFailsPairing() public {
        bytes32 id = groth16Gov.createProposal(keccak256("prop"), address(0), "");
        vm.expectRevert("Invalid ZK proof");
        groth16Gov.castVote(id, keccak256("v1"), true, ZERO_PROOF);
    }

    /// verifyProof called directly — returns false for zero proof.
    function test_Groth16_DirectCallReturnsFalse() public {
        uint256[4] memory signals =
            [uint256(keccak256("nullifier")), uint256(keccak256("proposal")), uint256(1), uint256(keccak256("root"))];
        bool result = realVerifier.verifyProof(ZERO_PROOF, signals);
        assertFalse(result);
    }

    /// verifyProof called directly — returns false for short proof.
    function test_Groth16_ShortProofReturnsFalse() public {
        uint256[4] memory signals;
        bool result = realVerifier.verifyProof(hex"beef", signals);
        assertFalse(result);
    }

    /// Field element > FIELD_MODULUS in signals → returns false.
    function test_Groth16_OutOfFieldSignalRejected() public {
        uint256 overField = 21888242871839275222246405745257275088548364400416034343698204186575808495617 + 1;
        uint256[4] memory signals = [overField, 0, 0, 0];
        bool result = realVerifier.verifyProof(ZERO_PROOF, signals);
        assertFalse(result);
    }

    // ── 3. Signal layout — castVote passes signals in circuit order ───────────

    /**
     * Verify the on-chain signal construction in castVote matches the circuit:
     *   signals[0] = nullifierHash
     *   signals[1] = proposalId
     *   signals[2] = voteYes ? 1 : 0
     *   signals[3] = membershipRoot
     *
     * Uses vm.expectCall to assert the exact calldata sent to the verifier,
     * including the signal array layout.  No custom verifier needed.
     */
    function test_SignalLayout_MatchesCircuit() public {
        MockVerifier mv = new MockVerifier();
        ZKSNGovernance captureGov = new ZKSNGovernance(address(mv), ROOT);

        bytes32 id = captureGov.createProposal(keccak256("p"), address(0), "");
        bytes32 nullifierHash = keccak256("my_nullifier");
        bytes memory proof = hex"aabbccdd";

        uint256[4] memory expectedSignals;
        expectedSignals[0] = uint256(nullifierHash); // signals[0] = nullifierHash
        expectedSignals[1] = uint256(id); // signals[1] = proposalId
        expectedSignals[2] = uint256(1); // signals[2] = 1 (voteYes=true)
        expectedSignals[3] = uint256(ROOT); // signals[3] = membershipRoot

        vm.expectCall(address(mv), abi.encodeCall(IVerifier.verifyProof, (proof, expectedSignals)));
        captureGov.castVote(id, nullifierHash, true, proof);
    }

    function test_SignalLayout_VoteNoIsZero() public {
        MockVerifier mv = new MockVerifier();
        ZKSNGovernance captureGov = new ZKSNGovernance(address(mv), ROOT);

        bytes32 id = captureGov.createProposal(keccak256("p"), address(0), "");
        bytes32 nullifierHash = keccak256("voter_no");
        bytes memory proof = hex"aabb";

        uint256[4] memory expectedSignals;
        expectedSignals[0] = uint256(nullifierHash);
        expectedSignals[1] = uint256(id);
        expectedSignals[2] = uint256(0); // signals[2] = 0 (voteYes=false)
        expectedSignals[3] = uint256(ROOT);

        vm.expectCall(address(mv), abi.encodeCall(IVerifier.verifyProof, (proof, expectedSignals)));
        captureGov.castVote(id, nullifierHash, false, proof);
    }

    // ── 4. Deployment — Groth16Verifier is the production verifier ───────────

    /// Confirm real governance is wired to Groth16Verifier, not MockVerifier.
    function test_Deployment_Groth16VerifierIsWired() public {
        assertEq(address(groth16Gov.verifier()), address(realVerifier));
    }

    /// MockVerifier address is different from Groth16Verifier.
    function test_Deployment_MockAndRealAreDistinct() public {
        assertFalse(address(mock) == address(realVerifier));
    }

    /// Groth16Verifier implements IVerifier interface.
    function test_Deployment_Groth16ImplementsIVerifier() public {
        IVerifier iv = IVerifier(address(realVerifier));
        uint256[4] memory signals;
        // Should not revert — returns false because VK is zeroed
        iv.verifyProof(ZERO_PROOF, signals);
    }

    // ── 5. PoseidonHasher — exact vector tests against circomlibjs output ────────
    //
    // All expected values computed with:
    //   const { buildPoseidon } = require("circomlibjs");
    //   const poseidon = await buildPoseidon();
    //   poseidon.F.toObject(poseidon([x]))           // t=2
    //   poseidon.F.toObject(poseidon([x, y]))        // t=3
    //
    // These values match the circuit and off-chain tree builder exactly.

    /// hashLeaf matches circomlibjs: poseidon([0]) = 19014214495641488759237505126948346942972912379615652741039992445865937985820
    function test_Poseidon_LeafZero() public view {
        assertEq(
            hasher.hashLeaf(0),
            19014214495641488759237505126948346942972912379615652741039992445865937985820
        );
    }

    /// hashLeaf matches circomlibjs: poseidon([1]) = 18586133768512220936620570745912940619677854269274689475585506675881198879027
    function test_Poseidon_LeafOne() public view {
        assertEq(
            hasher.hashLeaf(1),
            18586133768512220936620570745912940619677854269274689475585506675881198879027
        );
    }

    /// hashLeaf matches circomlibjs for ceremony secret.
    /// poseidon([12345678901234567890]) = 17610922722311195426938483481431943255028223790571250909270476711880232282197
    function test_Poseidon_LeafCeremonySecret() public view {
        assertEq(
            hasher.hashLeaf(12345678901234567890),
            17610922722311195426938483481431943255028223790571250909270476711880232282197
        );
    }

    /// hashLeaf output is in the BN254 scalar field.
    function test_Poseidon_LeafInField() public view {
        uint256 Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        assertLt(hasher.hashLeaf(999), Q);
    }

    /// hashNullifier matches circomlibjs: poseidon([0,0]) = 14744269619966411208579211824598458697587494354926760081771325075741142829156
    function test_Poseidon_NullifierZeroZero() public view {
        assertEq(
            hasher.hashNullifier(0, 0),
            14744269619966411208579211824598458697587494354926760081771325075741142829156
        );
    }

    /// hashNullifier matches circomlibjs for ceremony inputs.
    /// poseidon([12345678901234567890, 999888777666555]) = 21605468119089894529364334093527017674406608084847384275934021833321276526684
    function test_Poseidon_NullifierCeremonyInputs() public view {
        assertEq(
            hasher.hashNullifier(12345678901234567890, 999888777666555),
            21605468119089894529364334093527017674406608084847384275934021833321276526684
        );
    }

    /// hashNullifier matches circuit: REAL_NULLIFIER == hashNullifier(secret, REAL_PROPOSAL_ID)
    function test_Poseidon_NullifierMatchesCeremony() public view {
        assertEq(
            hasher.hashNullifier(12345678901234567890, REAL_PROPOSAL_ID),
            REAL_NULLIFIER
        );
    }

    /// hashNullifier is proposal-specific — same secret, different proposalId → different nullifier.
    function test_Poseidon_NullifierProposalSpecific() public view {
        uint256 secret = 99999;
        assertNotEq(
            hasher.hashNullifier(secret, 1),
            hasher.hashNullifier(secret, 2)
        );
    }

    /// hashNullifier output is in the BN254 scalar field.
    function test_Poseidon_NullifierInField() public view {
        uint256 Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        assertLt(hasher.hashNullifier(42, 7), Q);
    }

    /// hashNode matches circomlibjs: poseidon([1,2]) = 7853200120776062878684798364095072458815029376092732009249414926327459813530
    function test_Poseidon_NodeVector() public view {
        assertEq(
            hasher.hashNode(1, 2),
            7853200120776062878684798364095072458815029376092732009249414926327459813530
        );
    }

    /// hashNode is order-sensitive — Poseidon is not symmetric.
    function test_Poseidon_NodeOrderSensitive() public view {
        assertNotEq(hasher.hashNode(1, 2), hasher.hashNode(2, 1));
    }

    /// merkleRoot of the 16-leaf ceremony tree matches the circuit root.
    /// Leaf 0 = Poseidon(secret), leaves 1–15 = 0.
    function test_Poseidon_MerkleRootMatchesCeremony() public view {
        uint256[] memory leaves = new uint256[](16);
        leaves[0] = hasher.hashLeaf(12345678901234567890);
        // leaves[1..15] stay 0

        assertEq(hasher.merkleRoot(leaves), REAL_MEMBERSHIP_ROOT);
    }

    // ── 6. StrictMockVerifier — existing proof-approval tests ─────────────────

    function test_InvalidProofRejected() public {
        // StrictMockVerifier only approves PROOF (approved in setUp)
        ZKSNGovernance strictGov = new ZKSNGovernance(address(strict), ROOT);
        bytes32 id = strictGov.createProposal(keccak256("c"), address(0), "");
        vm.expectRevert("Invalid ZK proof");
        strictGov.castVote(id, keccak256("v1"), true, hex"badbad");
    }
}
