// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./IVerifier.sol";

// ── Groth16VerifierBase — generated by snarkjs zkey export solidityverifier ──
//
// DO NOT HAND-EDIT the VK constants below.
// Generated from: MembershipVote.circom (depth=20), pot15_final.ptau
// Ceremony: 3-contributor MPC + random beacon (feat/ceremony-mainnet).
//
// To regenerate after a new ceremony:
//   snarkjs zkey export solidityverifier \
//     ceremony/zkey_final.zkey \
//     governance/contracts/Groth16Verifier.sol

contract Groth16VerifierBase {
    // Scalar field size
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key — MembershipVote(depth=20)
    // alpha, beta, gamma are circuit-structure constants (depth-independent after phase 1 fix).
    // delta and IC change with every ceremony re-run.
    uint256 constant alphax  = 12282385098132280115600997204834850746531314943590361433170128020911864955271;
    uint256 constant alphay  = 7410496821888024096113532594592259891616017726763799175687040572116792404526;
    uint256 constant betax1  = 14424674331460052844239868486767574751166786646469029791237166380996206858430;
    uint256 constant betax2  = 4264620697378450193354494433411283886557629440544862493089024108248477570736;
    uint256 constant betay1  = 19281047192679723166150727461405876901243107226840976153736377111476103924384;
    uint256 constant betay2  = 12639120547239460801796259113851383773966212064178606380765734092346234677917;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 15560619824562473744189073915160070790175827590569421703707819459161041174340;
    uint256 constant deltax2 = 3191988381678685612370620646619802595265547745351187522261616309236774684936;
    uint256 constant deltay1 = 21194477893299753937709036620866420653327759073494881029804340112514768657127;
    uint256 constant deltay2 = 9500977738069911739050616423049302689515319470486487793385708726174882929331;

    uint256 constant IC0x = 17314315972325565711646743412534565115522630707059439781274453752239463016299;
    uint256 constant IC0y = 11460708601424109132809905248349002183427714592684640631877373147178845183500;
    uint256 constant IC1x = 56063653965915507762039958587622502090725883477488023021998123999608260443;
    uint256 constant IC1y = 8649381547757547764888948162321287716792380878030061053971439678819069791728;
    uint256 constant IC2x = 15900375952726670539497031804309034040050988926634869421409274402414507495623;
    uint256 constant IC2y = 9622639639141713112648584494294512258499053979313489109136817391561800825025;
    uint256 constant IC3x = 15269632990663702839660500659213526087641977883927862756129553778083236651197;
    uint256 constant IC3y = 5331607723370225434633368166050030511296544985937852023157070273299175811082;
    uint256 constant IC4x = 2021843955448830933304683807316732128984454752485181332352716837678412993443;
    uint256 constant IC4y = 17364357879620658706958889517983735777969919713393105638624501145899107912483;

    uint16 constant pVk      = 0;
    uint16 constant pPairing = 128;
    uint16 constant pLastMem = 896;

    /// @dev Internal Groth16 verification. pOff is the calldata byte offset of
    ///      the 256-byte proof blob: [pA(64B)][pB(128B)][pC(64B)].
    ///      pubSignals is the calldata offset of the uint256[4] signals array.
    function _verifyProof(uint256 pOff, uint256[4] calldata pubSignals) internal view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA_, pB_, pC_, pubSig, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk      := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSig,  0)))
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSig, 32)))
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSig, 64)))
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSig, 96)))

                // -A (negate y)
                mstore(_pPairing, calldataload(pA_))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA_, 32))), q))
                // B
                mstore(add(_pPairing, 64),  calldataload(pB_))
                mstore(add(_pPairing, 96),  calldataload(add(pB_,  32)))
                mstore(add(_pPairing, 128), calldataload(add(pB_,  64)))
                mstore(add(_pPairing, 160), calldataload(add(pB_,  96)))
                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))
                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                // C
                mstore(add(_pPairing, 576), calldataload(pC_))
                mstore(add(_pPairing, 608), calldataload(add(pC_, 32)))
                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate all signals are in field
            checkField(calldataload(add(pubSignals,  0)))
            checkField(calldataload(add(pubSignals, 32)))
            checkField(calldataload(add(pubSignals, 64)))
            checkField(calldataload(add(pubSignals, 96)))

            // proof layout: [pA: 0x00-0x3F][pB: 0x40-0xBF][pC: 0xC0-0xFF]
            let isValid := checkPairing(pOff, add(pOff, 0x40), add(pOff, 0xC0), pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}

// ── Groth16Verifier — IVerifier wrapper ──────────────────────────────────────
//
// Adapts the ZKSNGovernance IVerifier interface (bytes proof, uint256[4] signals)
// to the snarkjs-style split proof (pA, pB, pC, pubSignals).
//
// Proof encoding (256 bytes, abi.encode):
//   bytes = abi.encode(uint256[2] pA, uint256[2][2] pB, uint256[2] pC)
//
// G2 Fp2 coords must be in EIP-197 order: (imaginary, real).
// snarkjs proof.json stores them as (real, imaginary) — swap indices when encoding:
//
//   const proofBytes = ethers.AbiCoder.defaultAbiCoder().encode(
//     ["uint256[2]", "uint256[2][2]", "uint256[2]"],
//     [
//       [proof.pi_a[0], proof.pi_a[1]],
//       [[proof.pi_b[0][1], proof.pi_b[0][0]],   // swap: (im, re)
//        [proof.pi_b[1][1], proof.pi_b[1][0]]],  // swap: (im, re)
//       [proof.pi_c[0], proof.pi_c[1]]
//     ]
//   );

contract Groth16Verifier is Groth16VerifierBase, IVerifier {
    /**
     * @notice Verify a Groth16 MembershipVote proof.
     *
     * @param proof    ABI-encoded `(uint256[2] pA, uint256[2][2] pB, uint256[2] pC)` — 256 bytes.
     *                 Layout: [pA: 0x00-0x3F][pB: 0x40-0xBF][pC: 0xC0-0xFF]
     * @param signals  [nullifierHash, proposalId, voteYes, membershipRoot]
     * @return         true iff the proof is valid for these signals and the VK.
     */
    function verifyProof(bytes calldata proof, uint256[4] calldata signals)
        external
        view
        override
        returns (bool)
    {
        if (proof.length != 256) return false;

        uint256 pOff;
        assembly {
            pOff := proof.offset
        }

        return _verifyProof(pOff, signals);
    }
}
