// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./IVerifier.sol";

// ── Groth16VerifierBase — generated by snarkjs zkey export solidityverifier ──
//
// DO NOT HAND-EDIT the VK constants below.
// Generated from: MembershipVote.circom (depth=4), pot12_final.ptau
// Ceremony: 3-contributor MPC + random beacon (feat/ceremony-mainnet).

//
// To regenerate after a new ceremony:
//   snarkjs zkey export solidityverifier \
//     build/circuits/MembershipVote_final.zkey \
//     governance/contracts/Groth16Verifier.sol

contract Groth16VerifierBase {
    // Scalar field size
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key — MembershipVote(depth=4)
    uint256 constant alphax = 20242942742348168079301955704509828871903759818998712375829643365539531763603;
    uint256 constant alphay = 4353574706231690303910861315841790205137917491571855801996253736722002976275;
    uint256 constant betax1 = 21133004721348620483890113088050834025989720574121689103765737223806828350874;
    uint256 constant betax2 = 8517771684555639364230907707483339070753996680731890963115394089783023102584;
    uint256 constant betay1 = 11750851064431148893974595968269657805435076967963091961381900153645108332463;
    uint256 constant betay2 = 5414410354419622704329509872287488631317762425280966254002832148454404669881;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 13239159455209854885391344814099895864201722858832508895368568224256652230794;
    uint256 constant deltax2 = 12520334176007677924902946848108088073222406722938884588262680500371838060834;
    uint256 constant deltay1 = 9734361884712003728854433748012913745997966556128862002686768677239144794689;
    uint256 constant deltay2 = 1551210958028365771293531825981023128179307938762357170746470836686196907097;

    uint256 constant IC0x = 13191220692502808823198290899219019439500791333119289710728199735684568372073;
    uint256 constant IC0y = 11302962627370442445902623886631780358655326343058522449588932267844023164694;
    uint256 constant IC1x = 7875699891201183716993790008495884750801388090515260023525111454773126536059;
    uint256 constant IC1y = 21638096175766999548562177461839341892611578170016690477151466538484584827125;
    uint256 constant IC2x = 3726115788817672380539215461665655169704019906118097396430598873692797529474;
    uint256 constant IC2y = 3921548178874555701086212477971949665304810343985160571432743165429605016092;
    uint256 constant IC3x = 6930611171508098674921452342092372019895241015838450924433366583894116863200;
    uint256 constant IC3y = 4095721656721766754155395753137243441165043747897697104861082433333590875257;
    uint256 constant IC4x = 17236724019554794130534608986427664560116753882271053036841532983226746215295;
    uint256 constant IC4y = 15521573635140740016537217232788346173553158114444499089182930945843474204502;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;
    uint16 constant pLastMem = 896;

    /// @dev Internal Groth16 verification. pOff is the calldata byte offset of
    ///      the 256-byte proof blob: [pA(64B)][pB(128B)][pC(64B)].
    ///      pubSignals is the calldata offset of the uint256[4] signals array.
    function _verifyProof(uint256 pOff, uint256[4] calldata pubSignals) internal view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA_, pB_, pC_, pubSig, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSig, 0)))
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSig, 32)))
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSig, 64)))
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSig, 96)))

                // pA = pA_[0..1], negate y
                mstore(_pPairing, calldataload(pA_))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA_, 32))), q))
                // pB = pB_[0][0..1], pB_[1][0..1]
                mstore(add(_pPairing, 64), calldataload(pB_))
                mstore(add(_pPairing, 96), calldataload(add(pB_, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB_, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB_, 96)))
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                // pC = pC_[0..1]
                mstore(add(_pPairing, 576), calldataload(pC_))
                mstore(add(_pPairing, 608), calldataload(add(pC_, 32)))
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate all signals are in field
            checkField(calldataload(add(pubSignals, 0)))
            checkField(calldataload(add(pubSignals, 32)))
            checkField(calldataload(add(pubSignals, 64)))
            checkField(calldataload(add(pubSignals, 96)))

            // proof layout: [pA: 0x00-0x3F][pB: 0x40-0xBF][pC: 0xC0-0xFF]
            let isValid := checkPairing(pOff, add(pOff, 0x40), add(pOff, 0xC0), pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}

// ── Groth16Verifier — IVerifier wrapper ──────────────────────────────────────
//
// Adapts the ZKSNGovernance IVerifier interface (bytes proof, uint256[4] signals)
// to the snarkjs-style split proof (pA, pB, pC, pubSignals).
//
// Proof encoding (256 bytes, ABI-encoded):
//   bytes = abi.encode(uint256[2] pA, uint256[2][2] pB, uint256[2] pC)
//
// JS encoding helper:
//   const { groth16 } = require("snarkjs");
//   const { proof, publicSignals } = await groth16.fullProve(input, wasm, zkey);
//   const calldata = await groth16.exportSolidityCallData(proof, publicSignals);
//   // calldata is [pA, pB, pC, pubSignals] — encode pA/pB/pC as the proof bytes:
//   const proofBytes = ethers.AbiCoder.defaultAbiCoder().encode(
//     ["uint256[2]", "uint256[2][2]", "uint256[2]"],
//     [proof.pi_a.slice(0,2), [proof.pi_b[0], proof.pi_b[1]], proof.pi_c.slice(0,2)]
//   );

contract Groth16Verifier is Groth16VerifierBase, IVerifier {
    /**
     * @notice Verify a Groth16 MembershipVote proof.
     *
     * @param proof    ABI-encoded `(uint256[2] pA, uint256[2][2] pB, uint256[2] pC)` — 256 bytes.
     *                 Layout: [pA: 0x00-0x3F][pB: 0x40-0xBF][pC: 0xC0-0xFF]
     * @param signals  [nullifierHash, proposalId, voteYes, membershipRoot]
     * @return         true iff the proof is valid for these signals and the VK.
     *
     * JS proof encoding:
     *   const proofBytes = ethers.AbiCoder.defaultAbiCoder().encode(
     *     ["uint256[2]", "uint256[2][2]", "uint256[2]"],
     *     [proof.pi_a.slice(0,2), [proof.pi_b[0], proof.pi_b[1]], proof.pi_c.slice(0,2)]
     *   );
     */
    function verifyProof(bytes calldata proof, uint256[4] calldata signals)
        external
        view
        override
        returns (bool)
    {
        if (proof.length != 256) return false;

        // Extract the calldata byte offset of proof.data (skip the length word)
        // proof is a dynamic bytes calldata: [offset_ptr][length][data...]
        // proof.offset points to the start of the data bytes in calldata.
        uint256 pOff;
        assembly {
            pOff := proof.offset
        }

        return _verifyProof(pOff, signals);
    }
}
