// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./IVerifier.sol";

// ── Groth16VerifierBase — generated by snarkjs zkey export solidityverifier ──
//
// DO NOT HAND-EDIT the VK constants below.
// Generated from: MembershipVote.circom (depth=20), powersOfTau28_hez_final_15.ptau
// Ceremony: 3-contributor MPC + random beacon — Hermez pot28 (1000+ contributors).
//
// To regenerate after a new ceremony:
//   snarkjs zkey export solidityverifier \
//     ceremony/zkey_final.zkey \
//     governance/contracts/Groth16Verifier.sol

contract Groth16VerifierBase {
    // Scalar field size
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key — MembershipVote(depth=20)
    // alpha, beta, gamma are circuit-structure constants (depth-independent after phase 1 fix).
    // delta and IC change with every ceremony re-run.
uint256 constant alphax = 20491192805390485299153009773594534940189261866228447918068658471970481763042;
uint256 constant alphay = 9383485363053290200918347156157836566562967994039712273449902621266178545958;
uint256 constant betax1 = 4252822878758300859123897981450591353533073413197771768651442665752259397132;
uint256 constant betax2 = 6375614351688725206403948262868962793625744043794305715222011528459656738731;
uint256 constant betay1 = 21847035105528745403288232691147584728191162732299865338377159692350059136679;
uint256 constant betay2 = 10505242626370262277552901082094356697409835680220590971873171140371331206856;
uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
uint256 constant deltax1 = 18292736058557181127196921032897089864017299346670959391493857032893331019061;
uint256 constant deltax2 = 1748799018212643561734336107788856836581021858661675047000601141079932859249;
uint256 constant deltay1 = 19297574558885605867378746957216883542888011265075304869459646082342331892814;
uint256 constant deltay2 = 21238371744809587458399091958916116590245368028169171144086879543597061426200;

uint256 constant IC0x = 14771787788147687434918307645361687880168207526870828378127434106553292580979;
uint256 constant IC0y = 4409821717484303185951430149670345325188860361318557961667053404453595881287;
uint256 constant IC1x = 480462277759566407205181860812549378331290947563854389262424631009506969067;
uint256 constant IC1y = 2546819262716770573115234504275045964572295751750250064813480864992937187036;
uint256 constant IC2x = 7970367340001715336942240205091232217103245600161521417071214170088023941356;
uint256 constant IC2y = 6262740219210533964987642259117187874594353112933813683339131105703974857701;
uint256 constant IC3x = 18752417985923261616582548661312935968649310035828688968772368281569476039026;
uint256 constant IC3y = 7596121882616041903899636884656175369672840125674524633102711093796434103896;
uint256 constant IC4x = 16465215386921656960255380751958985183863741223379522787363109693785535724406;
uint256 constant IC4y = 4304351874528165661133204259358669012616244691017263276291043609358904734584;

    uint16 constant pVk      = 0;
    uint16 constant pPairing = 128;
    uint16 constant pLastMem = 896;

    /// @dev Internal Groth16 verification. pOff is the calldata byte offset of
    ///      the 256-byte proof blob: [pA(64B)][pB(128B)][pC(64B)].
    ///      pubSignals is the calldata offset of the uint256[4] signals array.
    function _verifyProof(uint256 pOff, uint256[4] calldata pubSignals) internal view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA_, pB_, pC_, pubSig, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk      := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSig,  0)))
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSig, 32)))
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSig, 64)))
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSig, 96)))

                // -A (negate y)
                mstore(_pPairing, calldataload(pA_))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA_, 32))), q))
                // B
                mstore(add(_pPairing, 64),  calldataload(pB_))
                mstore(add(_pPairing, 96),  calldataload(add(pB_,  32)))
                mstore(add(_pPairing, 128), calldataload(add(pB_,  64)))
                mstore(add(_pPairing, 160), calldataload(add(pB_,  96)))
                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))
                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                // C
                mstore(add(_pPairing, 576), calldataload(pC_))
                mstore(add(_pPairing, 608), calldataload(add(pC_, 32)))
                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate all signals are in field
            checkField(calldataload(add(pubSignals,  0)))
            checkField(calldataload(add(pubSignals, 32)))
            checkField(calldataload(add(pubSignals, 64)))
            checkField(calldataload(add(pubSignals, 96)))

            // proof layout: [pA: 0x00-0x3F][pB: 0x40-0xBF][pC: 0xC0-0xFF]
            let isValid := checkPairing(pOff, add(pOff, 0x40), add(pOff, 0xC0), pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}

// ── Groth16Verifier — IVerifier wrapper ──────────────────────────────────────
//
// Adapts the ZKSNGovernance IVerifier interface (bytes proof, uint256[4] signals)
// to the snarkjs-style split proof (pA, pB, pC, pubSignals).
//
// Proof encoding (256 bytes, abi.encode):
//   bytes = abi.encode(uint256[2] pA, uint256[2][2] pB, uint256[2] pC)
//
// G2 Fp2 coords must be in EIP-197 order: (imaginary, real).
// snarkjs proof.json stores them as (real, imaginary) — swap indices when encoding:
//
//   const proofBytes = ethers.AbiCoder.defaultAbiCoder().encode(
//     ["uint256[2]", "uint256[2][2]", "uint256[2]"],
//     [
//       [proof.pi_a[0], proof.pi_a[1]],
//       [[proof.pi_b[0][1], proof.pi_b[0][0]],   // swap: (im, re)
//        [proof.pi_b[1][1], proof.pi_b[1][0]]],  // swap: (im, re)
//       [proof.pi_c[0], proof.pi_c[1]]
//     ]
//   );

contract Groth16Verifier is Groth16VerifierBase, IVerifier {
    /**
     * @notice Verify a Groth16 MembershipVote proof.
     *
     * @param proof    ABI-encoded `(uint256[2] pA, uint256[2][2] pB, uint256[2] pC)` — 256 bytes.
     *                 Layout: [pA: 0x00-0x3F][pB: 0x40-0xBF][pC: 0xC0-0xFF]
     * @param signals  [nullifierHash, proposalId, voteYes, membershipRoot]
     * @return         true iff the proof is valid for these signals and the VK.
     */
    function verifyProof(bytes calldata proof, uint256[4] calldata signals)
        external
        view
        override
        returns (bool)
    {
        if (proof.length != 256) return false;

        uint256 pOff;
        assembly {
            pOff := proof.offset
        }

        return _verifyProof(pOff, signals);
    }
}
